"""Synthetic fixture builders for the run_all test suite.

Everything here is generated bytes — NO real client bytes anywhere (brief
rule). Every builder returns a *manifest* dict carrying the expectations
(counts, byte sizes, spot-check texts) so test files assert against the
fixture's own truth instead of hardcoding numbers.

Templates live next to this file under ``templates/``. The Achievements
templates are stored WITH whatever trailing whitespace they happen to
carry; the builder normalizes explicitly (``rstrip``) so the no-trailing-
newline property demanded by spec §6 is guaranteed at write time.
"""

from __future__ import annotations

import struct
import zlib
from pathlib import Path

TEMPLATES = Path(__file__).parent / "templates"

# Locale/category layout for the mini-loc fixture (spec §6 sketch):
# 2 locales x 3 categories; English carries the no-trailing-newline file;
# French is missing the Names category entirely (ledger skew).
MINILOC = {
    "English": {
        "Achievements": ["Clabber", "Creak in the Dark", "Dead juice"],
        "Menu": ["Start", "Settings", "Exit", "Language", "Back"],
        "Names": ["Mita", "Player", "Cappy"],
    },
    "French": {
        "Achievements": ["Caillé", "Grincement", "Jus mort"],
        "Menu": ["Démarrer", "Réglages", "Quitter", "Langue", "Retour"],
    },
}
NO_TRAILING_NL = ("English", "Achievements")


def png_bytes(width: int = 2, height: int = 2, rgb=(200, 40, 40)) -> bytes:
    """Minimal valid PNG via stdlib only (struct+zlib)."""
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    raw = b"".join(b"\x00" + bytes(rgb) * width for _ in range(height))
    crc32 = lambda t, d: struct.pack(">I", zlib.crc32(t + d) & 0xFFFFFFFF)
    return (
        b"\x89PNG\r\n\x1a\n"
        + struct.pack(">I", len(ihdr)) + b"IHDR" + ihdr + crc32(b"IHDR", ihdr)
        + struct.pack(">I", len(raw)) + b"IDAT" + zlib.compress(raw) + crc32(b"IDAT", raw)
        + struct.pack(">I", 0) + b"IEND" + crc32(b"IEND", b"")
    )


def _write(path: Path, data: bytes) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    return len(data)


def _pad(seed: bytes, size: int) -> bytes:
    out = bytearray(seed)
    i = 0
    while len(out) < size:
        out += bytes((65 + (i % 26),))
        i += 1
    return bytes(out[:size])


def build_language_tree(languages_dir: Path, spec=None, textures: dict | None = None,
                        psd_count: int = 0) -> dict:
    """Write Data\\Languages\\ per ``spec`` {locale: {category: [lines...]}}.

    The E1-proven quirk (deviation 3): category files carry NO trailing
    newline — so that is the default; files named in ``trailing_nl`` get
    one, giving the parser both shapes to chew on.
    """
    spec = MINILOC if spec is None else spec
    trailing_nl = {("English", "Menu")}
    textures = textures or {}
    man = {"locales": {}, "textures": {}, "psd": {}}
    for locale, cats in sorted(spec.items()):
        cat_man = {}
        for cat, lines in sorted(cats.items()):
            text = "\n".join(lines) + ("\n" if (locale, cat) in trailing_nl else "")
            n = _write(languages_dir / locale / f"{cat}.txt", text.encode("utf-8"))
            cat_man[cat] = {"lines": len(lines), "bytes": n,
                            "trailing_newline": (locale, cat) in trailing_nl}
        man["locales"][locale] = cat_man
        pngs = textures.get(locale, [])
        total = sum(_write(languages_dir / locale / "Textures" / name,
                           png_bytes(2, 2)) for name in pngs)
        man["textures"][locale] = {"count": len(pngs), "bytes": total}
        if psd_count:
            psd_bytes_total = 0
            for k in range(psd_count):
                psd_bytes_total += _write(
                    languages_dir / locale / "Textures" / f"art{k}.psd",
                    b"8BPS" + _pad(b"stub-psd", 512))
            man["psd"][locale] = {"count": psd_count, "bytes": psd_bytes_total}
    return man


def build_mini_loc(root: Path) -> dict:
    """Spec §6 mini-loc fixture: the 2-locale x 3-category parser tree,
    mounted on an otherwise minimal-but-valid game root (detect hard-fails
    on missing anchors, so loc tests need the full skeleton)."""
    man = build_mini_root(root)
    import shutil
    shutil.rmtree(root / "Data" / "Languages")
    man["languages"] = build_language_tree(root / "Data" / "Languages")
    man["texture_skew"] = {k: v["count"] for k, v in man["languages"]["textures"].items()}
    man["missing_categories"] = {"French": ["Names"]}
    return man


def build_mini_root(root: Path) -> dict:
    """Full synthetic game root R (spec §6 mini-root, brief-ruled fully
    synthetic — dummy exe/metadata shapes, no real client bytes).

    Returns a manifest with every number tests later assert against.
    """
    root.mkdir(parents=True, exist_ok=True)
    m: dict = {"root": str(root)}
    d = root / "MiSideFull_Data"

    # --- executables / anchors ------------------------------------------
    _write(root / "MiSideFull.exe", _pad(b"MZ stub exe MiSideFull", 4096))
    _write(root / "GameAssembly.dll", _pad(b"MZ stub GameAssembly (IL2CPP)", 65536))
    # global-metadata.dat: u32 LE at OFFSET 4 must be 29 (spec §S2) —
    # bytes 0..3 are the metadata magic, so the version lands after it.
    meta = (struct.pack("<I", 0xFAB11BAF) + struct.pack("<I", 29)
            + _pad(b"global-metadata stub v29", 8192))
    _write(d / "il2cpp_data" / "Metadata" / "global-metadata.dat", meta)

    # --- SerializedFile-class containers + stream siblings ---------------
    containers: dict[str, dict] = {}

    def container(name: str, seed: str, size: int, leading: str | None = None,
                  stream_size: int | None = None) -> None:
        body = (_pad(seed.encode(), size) if leading is None
                else leading.encode() + _pad(seed.encode(), size - len(leading)))
        containers[name] = {"bytes": _write(d / name, body)}
        if stream_size:
            containers[name]["stream_bytes"] = _write(
                d / f"{name}.resS", _pad(f"stream-of-{name}".encode(), stream_size))

    container("globalgamemanagers", "ggm", 4096, leading="2021.3.35f1")
    container("globalgamemanagers.assets", "ggma", 2048)
    container("resources.assets", "res", 32768, stream_size=8192)
    container("sharedassets0.assets", "sha0", 16384, stream_size=4096)
    container("level0", "lvl0", 8192)
    container("level3", "lvl3", 8192)
    m["containers"] = containers
    m["serialized_files"] = sorted(containers)
    m["serialized_total"] = sum(c["bytes"] for c in containers.values())
    m["streams"] = sorted(n for n, c in containers.items() if "stream_bytes" in c)
    m["stream_total"] = sum(c["stream_bytes"] for c in containers.values()
                            if "stream_bytes" in c)
    m["grand_total"] = m["serialized_total"] + m["stream_total"]

    # --- GI Enlighten tree (level3-only family, catalogue-only, R-E1-4) --
    gi_dir = d / "GI" / "level3" / "0123456789abcdef0123456789abcdef"
    gi_files = {}
    for ext in ("iws.sse", "rsc.sse", "vis", "caw", "ecm", "rgb"):
        gi_files[f"precomputed.{ext}"] = _write(
            gi_dir / f"precomputed.{ext}", _pad(f"gi-{ext}".encode(), 1024))
    m["gi"] = gi_files
    m["gi_total"] = sum(gi_files.values())

    # --- audio corpus (media carve-out: catalogue only, never copied) ---
    ogg_files = {}
    for i, sz in enumerate((3072, 5120, 9216)):
        ogg_files[f"voice_{i}.ogg"] = _write(d / f"voice_{i}.ogg",
                                             b"OggS" + _pad(b"stub-audio", sz))
    m["ogg"] = ogg_files
    m["ogg_total"] = sum(ogg_files.values())

    # --- localization ----------------------------------------------------
    tex = {"English": [f"ui_en_{i}.png" for i in range(4)],
           "Russian": [f"ui_ru_{i}.png" for i in range(4)],
           "Japanese": [f"ui_ja_{i}.png" for i in range(2)]}  # JA subset skew
    loc_spec = {
        "English": {
            "Achievements": (TEMPLATES / "achievements_en.txt").read_text("utf-8").splitlines(),
            "Menu": ["Start", "Settings", "Exit", "Language", "Back"],
            "Names": (TEMPLATES / "names_en.txt").read_text("utf-8").splitlines(),
        },
        "Russian": {
            "Achievements": [
                "Кислое молоко.", "Щелчок тьмы.", "Мёртвый сок.", "Пингвинобеда!",
                "Сейф жизни.", "Победа мухи.",
            ] + [f"Достижение {i}" for i in range(7, 26)] + ["Прогеймер"],
            "Menu": ["Старт", "Настройки", "Выход", "Язык", "Назад"],
            "Names": ["Мита", "Игрок", "Кэппи"],
        },
        "Japanese": {
            "Achievements": (TEMPLATES / "achievements_en.txt").read_text("utf-8").splitlines(),
            "Menu": ["スタート", "設定", "終了", "言語", "戻る"],
            # Names intentionally MISSING -> per-locale category skew (R-E1-3)
        },
    }
    lang_man = build_language_tree(root / "Data" / "Languages", loc_spec,
                                   textures=tex, psd_count=1)
    m["languages"] = lang_man
    en_ach = lang_man["locales"]["English"]["Achievements"]
    m["en_achievements_lines"] = en_ach["lines"]           # 26
    m["en_achievements_last"] = "Pro Gamer"                # line_index 25
    m["ru_achievements_first"] = "Кислое молоко."          # line_index 0
    m["missing_categories"] = {"Japanese": ["Names"]}      # ledger must record
    m["texture_skew"] = {k: v["count"] for k, v in lang_man["textures"].items()}

    # --- Data\Custom character templates (verbatim-copy family) ----------
    custom = {}
    for tpl in ("New (Sample)", "Original"):
        for part in ("Body", "Hair"):
            p = root / "Data" / "Custom" / tpl / f"{part}.png"
            data = png_bytes(4, 4, (10, 90, 200) if tpl == "New (Sample)" else (240, 240, 20))
            custom[f"{tpl}/{part}.png"] = {"path": str(p), "bytes": _write(p, data),
                                           "sha256": __import__("hashlib").sha256(data).hexdigest()}
    m["custom_pngs"] = custom

    # --- Voice Editor (Mono sub-app, content source row P7) --------------
    ve_managed = root / "Voice Editor" / "Miside Voice Editor_Data" / "Managed"
    m["voice_editor_dlls"] = sorted(
        name for name, sz in (
            ("Assembly-CSharp.dll", 24576),
            ("UnityEngine.CoreModule.dll", 12288),
            ("Assembly-CSharp-firstpass.dll", 8192),
        ) if _write(ve_managed / name, _pad(f"MZ stub {name}".encode(), sz)) or True)
    m["version_label"] = "VERSION 0.93L"
    _write(root / "Data" / "Version.txt", m["version_label"].encode() + b"\n")
    return m
